name: Basic-Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run a sample command
      run: echo "Hello, this is my first GitHub Action!"
